// This data is generated with the script generateFragments.ps1 in the root of the project and then paste here

type ClusterFragment = {
  id: string;
  cluster_id: string;
  image_id: string;
  url: string;
};

type ClusterFragmentList = ClusterFragment[];

export const clusterFragments: ClusterFragmentList = [
  {
    id: "a.1.1",
    cluster_id: "A",
    image_id: "a.1",
    url: "/cluster-images/fragments/A/a.1.1.png",
  },
  {
    id: "a.1.2",
    cluster_id: "A",
    image_id: "a.1",
    url: "/cluster-images/fragments/A/a.1.2.png",
  },
  {
    id: "a.1.3",
    cluster_id: "A",
    image_id: "a.1",
    url: "/cluster-images/fragments/A/a.1.3.png",
  },
  {
    id: "a.1.4",
    cluster_id: "A",
    image_id: "a.1",
    url: "/cluster-images/fragments/A/a.1.4.png",
  },
  {
    id: "a.10.1",
    cluster_id: "A",
    image_id: "a.10",
    url: "/cluster-images/fragments/A/a.10.1.png",
  },
  {
    id: "a.10.2",
    cluster_id: "A",
    image_id: "a.10",
    url: "/cluster-images/fragments/A/a.10.2.png",
  },
  {
    id: "a.10.3",
    cluster_id: "A",
    image_id: "a.10",
    url: "/cluster-images/fragments/A/a.10.3.png",
  },
  {
    id: "a.10.4",
    cluster_id: "A",
    image_id: "a.10",
    url: "/cluster-images/fragments/A/a.10.4.png",
  },
  {
    id: "a.2.1",
    cluster_id: "A",
    image_id: "a.2",
    url: "/cluster-images/fragments/A/a.2.1.png",
  },
  {
    id: "a.2.2",
    cluster_id: "A",
    image_id: "a.2",
    url: "/cluster-images/fragments/A/a.2.2.png",
  },
  {
    id: "a.2.3",
    cluster_id: "A",
    image_id: "a.2",
    url: "/cluster-images/fragments/A/a.2.3.png",
  },
  {
    id: "a.2.4",
    cluster_id: "A",
    image_id: "a.2",
    url: "/cluster-images/fragments/A/a.2.4.png",
  },
  {
    id: "a.2.5",
    cluster_id: "A",
    image_id: "a.2",
    url: "/cluster-images/fragments/A/a.2.5.png",
  },
  {
    id: "a.3.1",
    cluster_id: "A",
    image_id: "a.3",
    url: "/cluster-images/fragments/A/a.3.1.png",
  },
  {
    id: "a.3.2",
    cluster_id: "A",
    image_id: "a.3",
    url: "/cluster-images/fragments/A/a.3.2.png",
  },
  {
    id: "a.3.3",
    cluster_id: "A",
    image_id: "a.3",
    url: "/cluster-images/fragments/A/a.3.3.png",
  },
  {
    id: "a.3.4",
    cluster_id: "A",
    image_id: "a.3",
    url: "/cluster-images/fragments/A/a.3.4.png",
  },
  {
    id: "a.3.5",
    cluster_id: "A",
    image_id: "a.3",
    url: "/cluster-images/fragments/A/a.3.5.png",
  },
  {
    id: "a.4.1",
    cluster_id: "A",
    image_id: "a.4",
    url: "/cluster-images/fragments/A/a.4.1.png",
  },
  {
    id: "a.4.2",
    cluster_id: "A",
    image_id: "a.4",
    url: "/cluster-images/fragments/A/a.4.2.png",
  },
  {
    id: "a.4.3",
    cluster_id: "A",
    image_id: "a.4",
    url: "/cluster-images/fragments/A/a.4.3.png",
  },
  {
    id: "a.4.4",
    cluster_id: "A",
    image_id: "a.4",
    url: "/cluster-images/fragments/A/a.4.4.png",
  },
  {
    id: "a.5.1",
    cluster_id: "A",
    image_id: "a.5",
    url: "/cluster-images/fragments/A/a.5.1.png",
  },
  {
    id: "a.5.2",
    cluster_id: "A",
    image_id: "a.5",
    url: "/cluster-images/fragments/A/a.5.2.png",
  },
  {
    id: "a.5.3",
    cluster_id: "A",
    image_id: "a.5",
    url: "/cluster-images/fragments/A/a.5.3.png",
  },
  {
    id: "a.5.4",
    cluster_id: "A",
    image_id: "a.5",
    url: "/cluster-images/fragments/A/a.5.4.png",
  },
  {
    id: "a.6.1",
    cluster_id: "A",
    image_id: "a.6",
    url: "/cluster-images/fragments/A/a.6.1.png",
  },
  {
    id: "a.6.2",
    cluster_id: "A",
    image_id: "a.6",
    url: "/cluster-images/fragments/A/a.6.2.png",
  },
  {
    id: "a.6.3",
    cluster_id: "A",
    image_id: "a.6",
    url: "/cluster-images/fragments/A/a.6.3.png",
  },
  {
    id: "a.6.4",
    cluster_id: "A",
    image_id: "a.6",
    url: "/cluster-images/fragments/A/a.6.4.png",
  },
  {
    id: "a.6.5",
    cluster_id: "A",
    image_id: "a.6",
    url: "/cluster-images/fragments/A/a.6.5.png",
  },
  {
    id: "a.6.6",
    cluster_id: "A",
    image_id: "a.6",
    url: "/cluster-images/fragments/A/a.6.6.png",
  },
  {
    id: "a.7.1",
    cluster_id: "A",
    image_id: "a.7",
    url: "/cluster-images/fragments/A/a.7.1.png",
  },
  {
    id: "a.7.2",
    cluster_id: "A",
    image_id: "a.7",
    url: "/cluster-images/fragments/A/a.7.2.png",
  },
  {
    id: "a.7.3",
    cluster_id: "A",
    image_id: "a.7",
    url: "/cluster-images/fragments/A/a.7.3.png",
  },
  {
    id: "a.7.4",
    cluster_id: "A",
    image_id: "a.7",
    url: "/cluster-images/fragments/A/a.7.4.png",
  },
  {
    id: "a.7.5",
    cluster_id: "A",
    image_id: "a.7",
    url: "/cluster-images/fragments/A/a.7.5.png",
  },
  {
    id: "a.8.1",
    cluster_id: "A",
    image_id: "a.8",
    url: "/cluster-images/fragments/A/a.8.1.png",
  },
  {
    id: "a.8.2",
    cluster_id: "A",
    image_id: "a.8",
    url: "/cluster-images/fragments/A/a.8.2.png",
  },
  {
    id: "a.8.3",
    cluster_id: "A",
    image_id: "a.8",
    url: "/cluster-images/fragments/A/a.8.3.png",
  },
  {
    id: "a.8.4",
    cluster_id: "A",
    image_id: "a.8",
    url: "/cluster-images/fragments/A/a.8.4.png",
  },
  {
    id: "a.8.5",
    cluster_id: "A",
    image_id: "a.8",
    url: "/cluster-images/fragments/A/a.8.5.png",
  },
  {
    id: "a.9.1",
    cluster_id: "A",
    image_id: "a.9",
    url: "/cluster-images/fragments/A/a.9.1.png",
  },
  {
    id: "a.9.2",
    cluster_id: "A",
    image_id: "a.9",
    url: "/cluster-images/fragments/A/a.9.2.png",
  },
  {
    id: "a.9.3",
    cluster_id: "A",
    image_id: "a.9",
    url: "/cluster-images/fragments/A/a.9.3.png",
  },
  {
    id: "a.9.4",
    cluster_id: "A",
    image_id: "a.9",
    url: "/cluster-images/fragments/A/a.9.4.png",
  },
  {
    id: "b.1.1",
    cluster_id: "B",
    image_id: "b.1",
    url: "/cluster-images/fragments/B/b.1.1.png",
  },
  {
    id: "b.1.2",
    cluster_id: "B",
    image_id: "b.1",
    url: "/cluster-images/fragments/B/b.1.2.png",
  },
  {
    id: "b.1.3",
    cluster_id: "B",
    image_id: "b.1",
    url: "/cluster-images/fragments/B/b.1.3.png",
  },
  {
    id: "b.1.4",
    cluster_id: "B",
    image_id: "b.1",
    url: "/cluster-images/fragments/B/b.1.4.png",
  },
  {
    id: "b.2.1",
    cluster_id: "B",
    image_id: "b.2",
    url: "/cluster-images/fragments/B/b.2.1.png",
  },
  {
    id: "b.2.2",
    cluster_id: "B",
    image_id: "b.2",
    url: "/cluster-images/fragments/B/b.2.2.png",
  },
  {
    id: "b.2.3",
    cluster_id: "B",
    image_id: "b.2",
    url: "/cluster-images/fragments/B/b.2.3.png",
  },
  {
    id: "b.3.1",
    cluster_id: "B",
    image_id: "b.3",
    url: "/cluster-images/fragments/B/b.3.1.png",
  },
  {
    id: "b.3.2",
    cluster_id: "B",
    image_id: "b.3",
    url: "/cluster-images/fragments/B/b.3.2.png",
  },
  {
    id: "b.3.3",
    cluster_id: "B",
    image_id: "b.3",
    url: "/cluster-images/fragments/B/b.3.3.png",
  },
  {
    id: "b.4.1",
    cluster_id: "B",
    image_id: "b.4",
    url: "/cluster-images/fragments/B/b.4.1.png",
  },
  {
    id: "b.4.2",
    cluster_id: "B",
    image_id: "b.4",
    url: "/cluster-images/fragments/B/b.4.2.png",
  },
  {
    id: "b.4.3",
    cluster_id: "B",
    image_id: "b.4",
    url: "/cluster-images/fragments/B/b.4.3.png",
  },
  {
    id: "b.4.4",
    cluster_id: "B",
    image_id: "b.4",
    url: "/cluster-images/fragments/B/b.4.4.png",
  },
  {
    id: "b.5.1",
    cluster_id: "B",
    image_id: "b.5",
    url: "/cluster-images/fragments/B/b.5.1.png",
  },
  {
    id: "b.5.2",
    cluster_id: "B",
    image_id: "b.5",
    url: "/cluster-images/fragments/B/b.5.2.png",
  },
  {
    id: "b.5.3",
    cluster_id: "B",
    image_id: "b.5",
    url: "/cluster-images/fragments/B/b.5.3.png",
  },
  {
    id: "b.5.4",
    cluster_id: "B",
    image_id: "b.5",
    url: "/cluster-images/fragments/B/b.5.4.png",
  },
  {
    id: "b.5.5",
    cluster_id: "B",
    image_id: "b.5",
    url: "/cluster-images/fragments/B/b.5.5.png",
  },
  {
    id: "b.5.6",
    cluster_id: "B",
    image_id: "b.5",
    url: "/cluster-images/fragments/B/b.5.6.png",
  },
  {
    id: "b.6.1",
    cluster_id: "B",
    image_id: "b.6",
    url: "/cluster-images/fragments/B/b.6.1.png",
  },
  {
    id: "b.6.2",
    cluster_id: "B",
    image_id: "b.6",
    url: "/cluster-images/fragments/B/b.6.2.png",
  },
  {
    id: "b.6.3",
    cluster_id: "B",
    image_id: "b.6",
    url: "/cluster-images/fragments/B/b.6.3.png",
  },
  {
    id: "b.6.4",
    cluster_id: "B",
    image_id: "b.6",
    url: "/cluster-images/fragments/B/b.6.4.png",
  },
  {
    id: "b.6.5",
    cluster_id: "B",
    image_id: "b.6",
    url: "/cluster-images/fragments/B/b.6.5.png",
  },
  {
    id: "b.6.6",
    cluster_id: "B",
    image_id: "b.6",
    url: "/cluster-images/fragments/B/b.6.6.png",
  },
  {
    id: "b.6.7",
    cluster_id: "B",
    image_id: "b.6",
    url: "/cluster-images/fragments/B/b.6.7.png",
  },
  {
    id: "b.7.1",
    cluster_id: "B",
    image_id: "b.7",
    url: "/cluster-images/fragments/B/b.7.1.png",
  },
  {
    id: "b.7.2",
    cluster_id: "B",
    image_id: "b.7",
    url: "/cluster-images/fragments/B/b.7.2.png",
  },
  {
    id: "b.7.3",
    cluster_id: "B",
    image_id: "b.7",
    url: "/cluster-images/fragments/B/b.7.3.png",
  },
  {
    id: "b.7.4",
    cluster_id: "B",
    image_id: "b.7",
    url: "/cluster-images/fragments/B/b.7.4.png",
  },
  {
    id: "b.7.5",
    cluster_id: "B",
    image_id: "b.7",
    url: "/cluster-images/fragments/B/b.7.5.png",
  },
  {
    id: "b.7.6",
    cluster_id: "B",
    image_id: "b.7",
    url: "/cluster-images/fragments/B/b.7.6.png",
  },
  {
    id: "b.7.7",
    cluster_id: "B",
    image_id: "b.7",
    url: "/cluster-images/fragments/B/b.7.7.png",
  },
  {
    id: "b.8.1",
    cluster_id: "B",
    image_id: "b.8",
    url: "/cluster-images/fragments/B/b.8.1.png",
  },
  {
    id: "b.8.2",
    cluster_id: "B",
    image_id: "b.8",
    url: "/cluster-images/fragments/B/b.8.2.png",
  },
  {
    id: "b.8.3",
    cluster_id: "B",
    image_id: "b.8",
    url: "/cluster-images/fragments/B/b.8.3.png",
  },
  {
    id: "b.8.4",
    cluster_id: "B",
    image_id: "b.8",
    url: "/cluster-images/fragments/B/b.8.4.png",
  },
  {
    id: "b.8.5",
    cluster_id: "B",
    image_id: "b.8",
    url: "/cluster-images/fragments/B/b.8.5.png",
  },
  {
    id: "b.8.6",
    cluster_id: "B",
    image_id: "b.8",
    url: "/cluster-images/fragments/B/b.8.6.png",
  },
  {
    id: "b.8.7",
    cluster_id: "B",
    image_id: "b.8",
    url: "/cluster-images/fragments/B/b.8.7.png",
  },
  {
    id: "b.9.1",
    cluster_id: "B",
    image_id: "b.9",
    url: "/cluster-images/fragments/B/b.9.1.png",
  },
  {
    id: "b.9.2",
    cluster_id: "B",
    image_id: "b.9",
    url: "/cluster-images/fragments/B/b.9.2.png",
  },
  {
    id: "b.9.3",
    cluster_id: "B",
    image_id: "b.9",
    url: "/cluster-images/fragments/B/b.9.3.png",
  },
  {
    id: "b.9.4",
    cluster_id: "B",
    image_id: "b.9",
    url: "/cluster-images/fragments/B/b.9.4.png",
  },
  {
    id: "b.9.5",
    cluster_id: "B",
    image_id: "b.9",
    url: "/cluster-images/fragments/B/b.9.5.png",
  },
  {
    id: "c.1.1",
    cluster_id: "C",
    image_id: "c.1",
    url: "/cluster-images/fragments/C/c.1.1.png",
  },
  {
    id: "c.1.2",
    cluster_id: "C",
    image_id: "c.1",
    url: "/cluster-images/fragments/C/c.1.2.png",
  },
  {
    id: "c.1.3",
    cluster_id: "C",
    image_id: "c.1",
    url: "/cluster-images/fragments/C/c.1.3.png",
  },
  {
    id: "c.1.4",
    cluster_id: "C",
    image_id: "c.1",
    url: "/cluster-images/fragments/C/c.1.4.png",
  },
  {
    id: "c.10.1",
    cluster_id: "C",
    image_id: "c.10",
    url: "/cluster-images/fragments/C/c.10.1.png",
  },
  {
    id: "c.10.2",
    cluster_id: "C",
    image_id: "c.10",
    url: "/cluster-images/fragments/C/c.10.2.png",
  },
  {
    id: "c.10.3",
    cluster_id: "C",
    image_id: "c.10",
    url: "/cluster-images/fragments/C/c.10.3.png",
  },
  {
    id: "c.10.4",
    cluster_id: "C",
    image_id: "c.10",
    url: "/cluster-images/fragments/C/c.10.4.png",
  },
  {
    id: "c.10.5",
    cluster_id: "C",
    image_id: "c.10",
    url: "/cluster-images/fragments/C/c.10.5.png",
  },
  {
    id: "c.10.6",
    cluster_id: "C",
    image_id: "c.10",
    url: "/cluster-images/fragments/C/c.10.6.png",
  },
  {
    id: "c.10.7",
    cluster_id: "C",
    image_id: "c.10",
    url: "/cluster-images/fragments/C/c.10.7.png",
  },
  {
    id: "c.2.1",
    cluster_id: "C",
    image_id: "c.2",
    url: "/cluster-images/fragments/C/c.2.1.png",
  },
  {
    id: "c.2.2",
    cluster_id: "C",
    image_id: "c.2",
    url: "/cluster-images/fragments/C/c.2.2.png",
  },
  {
    id: "c.2.3",
    cluster_id: "C",
    image_id: "c.2",
    url: "/cluster-images/fragments/C/c.2.3.png",
  },
  {
    id: "c.2.4",
    cluster_id: "C",
    image_id: "c.2",
    url: "/cluster-images/fragments/C/c.2.4.png",
  },
  {
    id: "c.3.1",
    cluster_id: "C",
    image_id: "c.3",
    url: "/cluster-images/fragments/C/c.3.1.png",
  },
  {
    id: "c.3.2",
    cluster_id: "C",
    image_id: "c.3",
    url: "/cluster-images/fragments/C/c.3.2.png",
  },
  {
    id: "c.3.3",
    cluster_id: "C",
    image_id: "c.3",
    url: "/cluster-images/fragments/C/c.3.3.png",
  },
  {
    id: "c.3.4",
    cluster_id: "C",
    image_id: "c.3",
    url: "/cluster-images/fragments/C/c.3.4.png",
  },
  {
    id: "c.4.1",
    cluster_id: "C",
    image_id: "c.4",
    url: "/cluster-images/fragments/C/c.4.1.png",
  },
  {
    id: "c.4.2",
    cluster_id: "C",
    image_id: "c.4",
    url: "/cluster-images/fragments/C/c.4.2.png",
  },
  {
    id: "c.4.3",
    cluster_id: "C",
    image_id: "c.4",
    url: "/cluster-images/fragments/C/c.4.3.png",
  },
  {
    id: "c.4.4",
    cluster_id: "C",
    image_id: "c.4",
    url: "/cluster-images/fragments/C/c.4.4.png",
  },
  {
    id: "c.4.5",
    cluster_id: "C",
    image_id: "c.4",
    url: "/cluster-images/fragments/C/c.4.5.png",
  },
  {
    id: "c.5.1",
    cluster_id: "C",
    image_id: "c.5",
    url: "/cluster-images/fragments/C/c.5.1.png",
  },
  {
    id: "c.5.2",
    cluster_id: "C",
    image_id: "c.5",
    url: "/cluster-images/fragments/C/c.5.2.png",
  },
  {
    id: "c.5.3",
    cluster_id: "C",
    image_id: "c.5",
    url: "/cluster-images/fragments/C/c.5.3.png",
  },
  {
    id: "c.5.4",
    cluster_id: "C",
    image_id: "c.5",
    url: "/cluster-images/fragments/C/c.5.4.png",
  },
  {
    id: "c.5.5",
    cluster_id: "C",
    image_id: "c.5",
    url: "/cluster-images/fragments/C/c.5.5.png",
  },
  {
    id: "c.6.1",
    cluster_id: "C",
    image_id: "c.6",
    url: "/cluster-images/fragments/C/c.6.1.png",
  },
  {
    id: "c.6.2",
    cluster_id: "C",
    image_id: "c.6",
    url: "/cluster-images/fragments/C/c.6.2.png",
  },
  {
    id: "c.6.3",
    cluster_id: "C",
    image_id: "c.6",
    url: "/cluster-images/fragments/C/c.6.3.png",
  },
  {
    id: "c.7.1",
    cluster_id: "C",
    image_id: "c.7",
    url: "/cluster-images/fragments/C/c.7.1.png",
  },
  {
    id: "c.7.2",
    cluster_id: "C",
    image_id: "c.7",
    url: "/cluster-images/fragments/C/c.7.2.png",
  },
  {
    id: "c.7.3",
    cluster_id: "C",
    image_id: "c.7",
    url: "/cluster-images/fragments/C/c.7.3.png",
  },
  {
    id: "c.7.4",
    cluster_id: "C",
    image_id: "c.7",
    url: "/cluster-images/fragments/C/c.7.4.png",
  },
  {
    id: "c.8.1",
    cluster_id: "C",
    image_id: "c.8",
    url: "/cluster-images/fragments/C/c.8.1.png",
  },
  {
    id: "c.8.2",
    cluster_id: "C",
    image_id: "c.8",
    url: "/cluster-images/fragments/C/c.8.2.png",
  },
  {
    id: "c.8.3",
    cluster_id: "C",
    image_id: "c.8",
    url: "/cluster-images/fragments/C/c.8.3.png",
  },
  {
    id: "c.8.4",
    cluster_id: "C",
    image_id: "c.8",
    url: "/cluster-images/fragments/C/c.8.4.png",
  },
  {
    id: "c.8.5",
    cluster_id: "C",
    image_id: "c.8",
    url: "/cluster-images/fragments/C/c.8.5.png",
  },
  {
    id: "c.8.6",
    cluster_id: "C",
    image_id: "c.8",
    url: "/cluster-images/fragments/C/c.8.6.png",
  },
  {
    id: "c.9.1",
    cluster_id: "C",
    image_id: "c.9",
    url: "/cluster-images/fragments/C/c.9.1.png",
  },
  {
    id: "c.9.2",
    cluster_id: "C",
    image_id: "c.9",
    url: "/cluster-images/fragments/C/c.9.2.png",
  },
  {
    id: "c.9.3",
    cluster_id: "C",
    image_id: "c.9",
    url: "/cluster-images/fragments/C/c.9.3.png",
  },
  {
    id: "c.9.4",
    cluster_id: "C",
    image_id: "c.9",
    url: "/cluster-images/fragments/C/c.9.4.png",
  },
  {
    id: "c.9.5",
    cluster_id: "C",
    image_id: "c.9",
    url: "/cluster-images/fragments/C/c.9.5.png",
  },
  {
    id: "D.1.1",
    cluster_id: "D",
    image_id: "D.1",
    url: "/cluster-images/fragments/D/D.1.1.png",
  },
  {
    id: "D.1.2",
    cluster_id: "D",
    image_id: "D.1",
    url: "/cluster-images/fragments/D/D.1.2.png",
  },
  {
    id: "D.1.3",
    cluster_id: "D",
    image_id: "D.1",
    url: "/cluster-images/fragments/D/D.1.3.png",
  },
  {
    id: "d.10.1",
    cluster_id: "D",
    image_id: "d.10",
    url: "/cluster-images/fragments/D/d.10.1.png",
  },
  {
    id: "d.10.2",
    cluster_id: "D",
    image_id: "d.10",
    url: "/cluster-images/fragments/D/d.10.2.png",
  },
  {
    id: "d.10.3",
    cluster_id: "D",
    image_id: "d.10",
    url: "/cluster-images/fragments/D/d.10.3.png",
  },
  {
    id: "d.10.4",
    cluster_id: "D",
    image_id: "d.10",
    url: "/cluster-images/fragments/D/d.10.4.png",
  },
  {
    id: "d.2.1",
    cluster_id: "D",
    image_id: "d.2",
    url: "/cluster-images/fragments/D/d.2.1.png",
  },
  {
    id: "D.2.2",
    cluster_id: "D",
    image_id: "D.2",
    url: "/cluster-images/fragments/D/D.2.2.png",
  },
  {
    id: "D.2.3",
    cluster_id: "D",
    image_id: "D.2",
    url: "/cluster-images/fragments/D/D.2.3.png",
  },
  {
    id: "D.2.4",
    cluster_id: "D",
    image_id: "D.2",
    url: "/cluster-images/fragments/D/D.2.4.png",
  },
  {
    id: "D.3.1",
    cluster_id: "D",
    image_id: "D.3",
    url: "/cluster-images/fragments/D/D.3.1.png",
  },
  {
    id: "D.3.2",
    cluster_id: "D",
    image_id: "D.3",
    url: "/cluster-images/fragments/D/D.3.2.png",
  },
  {
    id: "D.3.3",
    cluster_id: "D",
    image_id: "D.3",
    url: "/cluster-images/fragments/D/D.3.3.png",
  },
  {
    id: "D.3.4",
    cluster_id: "D",
    image_id: "D.3",
    url: "/cluster-images/fragments/D/D.3.4.png",
  },
  {
    id: "D.4.1",
    cluster_id: "D",
    image_id: "D.4",
    url: "/cluster-images/fragments/D/D.4.1.png",
  },
  {
    id: "D.4.2",
    cluster_id: "D",
    image_id: "D.4",
    url: "/cluster-images/fragments/D/D.4.2.png",
  },
  {
    id: "D.4.3",
    cluster_id: "D",
    image_id: "D.4",
    url: "/cluster-images/fragments/D/D.4.3.png",
  },
  {
    id: "d.4.4",
    cluster_id: "D",
    image_id: "d.4",
    url: "/cluster-images/fragments/D/d.4.4.png",
  },
  {
    id: "D.5.1",
    cluster_id: "D",
    image_id: "D.5",
    url: "/cluster-images/fragments/D/D.5.1.png",
  },
  {
    id: "d.5.2",
    cluster_id: "D",
    image_id: "d.5",
    url: "/cluster-images/fragments/D/d.5.2.png",
  },
  {
    id: "d.5.3",
    cluster_id: "D",
    image_id: "d.5",
    url: "/cluster-images/fragments/D/d.5.3.png",
  },
  {
    id: "d.5.4",
    cluster_id: "D",
    image_id: "d.5",
    url: "/cluster-images/fragments/D/d.5.4.png",
  },
  {
    id: "d.6.1",
    cluster_id: "D",
    image_id: "d.6",
    url: "/cluster-images/fragments/D/d.6.1.png",
  },
  {
    id: "d.6.2",
    cluster_id: "D",
    image_id: "d.6",
    url: "/cluster-images/fragments/D/d.6.2.png",
  },
  {
    id: "d.6.3",
    cluster_id: "D",
    image_id: "d.6",
    url: "/cluster-images/fragments/D/d.6.3.png",
  },
  {
    id: "d.6.4",
    cluster_id: "D",
    image_id: "d.6",
    url: "/cluster-images/fragments/D/d.6.4.png",
  },
  {
    id: "d.7.1",
    cluster_id: "D",
    image_id: "d.7",
    url: "/cluster-images/fragments/D/d.7.1.png",
  },
  {
    id: "d.7.2",
    cluster_id: "D",
    image_id: "d.7",
    url: "/cluster-images/fragments/D/d.7.2.png",
  },
  {
    id: "d.7.3",
    cluster_id: "D",
    image_id: "d.7",
    url: "/cluster-images/fragments/D/d.7.3.png",
  },
  {
    id: "d.7.4",
    cluster_id: "D",
    image_id: "d.7",
    url: "/cluster-images/fragments/D/d.7.4.png",
  },
  {
    id: "d.8.1",
    cluster_id: "D",
    image_id: "d.8",
    url: "/cluster-images/fragments/D/d.8.1.png",
  },
  {
    id: "d.8.2",
    cluster_id: "D",
    image_id: "d.8",
    url: "/cluster-images/fragments/D/d.8.2.png",
  },
  {
    id: "d.8.3",
    cluster_id: "D",
    image_id: "d.8",
    url: "/cluster-images/fragments/D/d.8.3.png",
  },
  {
    id: "d.8.4",
    cluster_id: "D",
    image_id: "d.8",
    url: "/cluster-images/fragments/D/d.8.4.png",
  },
  {
    id: "d.9.1",
    cluster_id: "D",
    image_id: "d.9",
    url: "/cluster-images/fragments/D/d.9.1.png",
  },
  {
    id: "d.9.2",
    cluster_id: "D",
    image_id: "d.9",
    url: "/cluster-images/fragments/D/d.9.2.png",
  },
  {
    id: "d.9.3",
    cluster_id: "D",
    image_id: "d.9",
    url: "/cluster-images/fragments/D/d.9.3.png",
  },
  {
    id: "d.9.4",
    cluster_id: "D",
    image_id: "d.9",
    url: "/cluster-images/fragments/D/d.9.4.png",
  },
  {
    id: "e.1.1",
    cluster_id: "E",
    image_id: "e.1",
    url: "/cluster-images/fragments/E/e.1.1.png",
  },
  {
    id: "e.1.2",
    cluster_id: "E",
    image_id: "e.1",
    url: "/cluster-images/fragments/E/e.1.2.png",
  },
  {
    id: "e.1.3",
    cluster_id: "E",
    image_id: "e.1",
    url: "/cluster-images/fragments/E/e.1.3.png",
  },
  {
    id: "e.1.4",
    cluster_id: "E",
    image_id: "e.1",
    url: "/cluster-images/fragments/E/e.1.4.png",
  },
  {
    id: "e.2.1",
    cluster_id: "E",
    image_id: "e.2",
    url: "/cluster-images/fragments/E/e.2.1.png",
  },
  {
    id: "e.2.2",
    cluster_id: "E",
    image_id: "e.2",
    url: "/cluster-images/fragments/E/e.2.2.png",
  },
  {
    id: "e.2.3",
    cluster_id: "E",
    image_id: "e.2",
    url: "/cluster-images/fragments/E/e.2.3.png",
  },
  {
    id: "e.2.4",
    cluster_id: "E",
    image_id: "e.2",
    url: "/cluster-images/fragments/E/e.2.4.png",
  },
  {
    id: "e.3.1",
    cluster_id: "E",
    image_id: "e.3",
    url: "/cluster-images/fragments/E/e.3.1.png",
  },
  {
    id: "e.3.2",
    cluster_id: "E",
    image_id: "e.3",
    url: "/cluster-images/fragments/E/e.3.2.png",
  },
  {
    id: "e.3.3",
    cluster_id: "E",
    image_id: "e.3",
    url: "/cluster-images/fragments/E/e.3.3.png",
  },
  {
    id: "e.3.4",
    cluster_id: "E",
    image_id: "e.3",
    url: "/cluster-images/fragments/E/e.3.4.png",
  },
  {
    id: "e.4.1",
    cluster_id: "E",
    image_id: "e.4",
    url: "/cluster-images/fragments/E/e.4.1.png",
  },
  {
    id: "e.4.2",
    cluster_id: "E",
    image_id: "e.4",
    url: "/cluster-images/fragments/E/e.4.2.png",
  },
  {
    id: "e.4.3",
    cluster_id: "E",
    image_id: "e.4",
    url: "/cluster-images/fragments/E/e.4.3.png",
  },
  {
    id: "e.4.4",
    cluster_id: "E",
    image_id: "e.4",
    url: "/cluster-images/fragments/E/e.4.4.png",
  },
  {
    id: "e.5.1",
    cluster_id: "E",
    image_id: "e.5",
    url: "/cluster-images/fragments/E/e.5.1.png",
  },
  {
    id: "e.5.2",
    cluster_id: "E",
    image_id: "e.5",
    url: "/cluster-images/fragments/E/e.5.2.png",
  },
  {
    id: "e.5.3",
    cluster_id: "E",
    image_id: "e.5",
    url: "/cluster-images/fragments/E/e.5.3.png",
  },
  {
    id: "e.6.1",
    cluster_id: "E",
    image_id: "e.6",
    url: "/cluster-images/fragments/E/e.6.1.png",
  },
  {
    id: "e.6.2",
    cluster_id: "E",
    image_id: "e.6",
    url: "/cluster-images/fragments/E/e.6.2.png",
  },
  {
    id: "e.6.3",
    cluster_id: "E",
    image_id: "e.6",
    url: "/cluster-images/fragments/E/e.6.3.png",
  },
  {
    id: "e.6.4",
    cluster_id: "E",
    image_id: "e.6",
    url: "/cluster-images/fragments/E/e.6.4.png",
  },
  {
    id: "e.7.1",
    cluster_id: "E",
    image_id: "e.7",
    url: "/cluster-images/fragments/E/e.7.1.png",
  },
  {
    id: "e.7.2",
    cluster_id: "E",
    image_id: "e.7",
    url: "/cluster-images/fragments/E/e.7.2.png",
  },
  {
    id: "e.7.3",
    cluster_id: "E",
    image_id: "e.7",
    url: "/cluster-images/fragments/E/e.7.3.png",
  },
  {
    id: "e.7.4",
    cluster_id: "E",
    image_id: "e.7",
    url: "/cluster-images/fragments/E/e.7.4.png",
  },
  {
    id: "e.8.1",
    cluster_id: "E",
    image_id: "e.8",
    url: "/cluster-images/fragments/E/e.8.1.png",
  },
  {
    id: "e.8.2",
    cluster_id: "E",
    image_id: "e.8",
    url: "/cluster-images/fragments/E/e.8.2.png",
  },
  {
    id: "e.8.3",
    cluster_id: "E",
    image_id: "e.8",
    url: "/cluster-images/fragments/E/e.8.3.png",
  },
  {
    id: "e.8.4",
    cluster_id: "E",
    image_id: "e.8",
    url: "/cluster-images/fragments/E/e.8.4.png",
  },
  {
    id: "e.9.1",
    cluster_id: "E",
    image_id: "e.9",
    url: "/cluster-images/fragments/E/e.9.1.png",
  },
  {
    id: "e.9.2",
    cluster_id: "E",
    image_id: "e.9",
    url: "/cluster-images/fragments/E/e.9.2.png",
  },
  {
    id: "e.9.3",
    cluster_id: "E",
    image_id: "e.9",
    url: "/cluster-images/fragments/E/e.9.3.png",
  },
  {
    id: "e.9.4",
    cluster_id: "E",
    image_id: "e.9",
    url: "/cluster-images/fragments/E/e.9.4.png",
  },
  {
    id: "f.1.1",
    cluster_id: "F",
    image_id: "f.1",
    url: "/cluster-images/fragments/F/f.1.1.png",
  },
  {
    id: "f.1.2",
    cluster_id: "F",
    image_id: "f.1",
    url: "/cluster-images/fragments/F/f.1.2.png",
  },
  {
    id: "f.1.3",
    cluster_id: "F",
    image_id: "f.1",
    url: "/cluster-images/fragments/F/f.1.3.png",
  },
  {
    id: "f.10.1",
    cluster_id: "F",
    image_id: "f.10",
    url: "/cluster-images/fragments/F/f.10.1.png",
  },
  {
    id: "f.10.2",
    cluster_id: "F",
    image_id: "f.10",
    url: "/cluster-images/fragments/F/f.10.2.png",
  },
  {
    id: "f.10.3",
    cluster_id: "F",
    image_id: "f.10",
    url: "/cluster-images/fragments/F/f.10.3.png",
  },
  {
    id: "f.10.4",
    cluster_id: "F",
    image_id: "f.10",
    url: "/cluster-images/fragments/F/f.10.4.png",
  },
  {
    id: "f.2.1",
    cluster_id: "F",
    image_id: "f.2",
    url: "/cluster-images/fragments/F/f.2.1.png",
  },
  {
    id: "f.2.2",
    cluster_id: "F",
    image_id: "f.2",
    url: "/cluster-images/fragments/F/f.2.2.png",
  },
  {
    id: "f.2.3",
    cluster_id: "F",
    image_id: "f.2",
    url: "/cluster-images/fragments/F/f.2.3.png",
  },
  {
    id: "f.3.1",
    cluster_id: "F",
    image_id: "f.3",
    url: "/cluster-images/fragments/F/f.3.1.png",
  },
  {
    id: "f.3.2",
    cluster_id: "F",
    image_id: "f.3",
    url: "/cluster-images/fragments/F/f.3.2.png",
  },
  {
    id: "f.3.3",
    cluster_id: "F",
    image_id: "f.3",
    url: "/cluster-images/fragments/F/f.3.3.png",
  },
  {
    id: "f.3.4",
    cluster_id: "F",
    image_id: "f.3",
    url: "/cluster-images/fragments/F/f.3.4.png",
  },
  {
    id: "f.4.1",
    cluster_id: "F",
    image_id: "f.4",
    url: "/cluster-images/fragments/F/f.4.1.png",
  },
  {
    id: "f.4.2",
    cluster_id: "F",
    image_id: "f.4",
    url: "/cluster-images/fragments/F/f.4.2.png",
  },
  {
    id: "f.4.3",
    cluster_id: "F",
    image_id: "f.4",
    url: "/cluster-images/fragments/F/f.4.3.png",
  },
  {
    id: "f.4.4",
    cluster_id: "F",
    image_id: "f.4",
    url: "/cluster-images/fragments/F/f.4.4.png",
  },
  {
    id: "f.5.1",
    cluster_id: "F",
    image_id: "f.5",
    url: "/cluster-images/fragments/F/f.5.1.png",
  },
  {
    id: "f.5.2",
    cluster_id: "F",
    image_id: "f.5",
    url: "/cluster-images/fragments/F/f.5.2.png",
  },
  {
    id: "f.5.3",
    cluster_id: "F",
    image_id: "f.5",
    url: "/cluster-images/fragments/F/f.5.3.png",
  },
  {
    id: "f.5.4",
    cluster_id: "F",
    image_id: "f.5",
    url: "/cluster-images/fragments/F/f.5.4.png",
  },
  {
    id: "f.6.1",
    cluster_id: "F",
    image_id: "f.6",
    url: "/cluster-images/fragments/F/f.6.1.png",
  },
  {
    id: "f.6.2",
    cluster_id: "F",
    image_id: "f.6",
    url: "/cluster-images/fragments/F/f.6.2.png",
  },
  {
    id: "f.6.3",
    cluster_id: "F",
    image_id: "f.6",
    url: "/cluster-images/fragments/F/f.6.3.png",
  },
  {
    id: "f.6.4",
    cluster_id: "F",
    image_id: "f.6",
    url: "/cluster-images/fragments/F/f.6.4.png",
  },
  {
    id: "f.7.1",
    cluster_id: "F",
    image_id: "f.7",
    url: "/cluster-images/fragments/F/f.7.1.png",
  },
  {
    id: "f.7.2",
    cluster_id: "F",
    image_id: "f.7",
    url: "/cluster-images/fragments/F/f.7.2.png",
  },
  {
    id: "f.7.3",
    cluster_id: "F",
    image_id: "f.7",
    url: "/cluster-images/fragments/F/f.7.3.png",
  },
  {
    id: "f.8.1",
    cluster_id: "F",
    image_id: "f.8",
    url: "/cluster-images/fragments/F/f.8.1.png",
  },
  {
    id: "f.8.2",
    cluster_id: "F",
    image_id: "f.8",
    url: "/cluster-images/fragments/F/f.8.2.png",
  },
  {
    id: "f.8.3",
    cluster_id: "F",
    image_id: "f.8",
    url: "/cluster-images/fragments/F/f.8.3.png",
  },
  {
    id: "f.8.4",
    cluster_id: "F",
    image_id: "f.8",
    url: "/cluster-images/fragments/F/f.8.4.png",
  },
  {
    id: "f.9.1",
    cluster_id: "F",
    image_id: "f.9",
    url: "/cluster-images/fragments/F/f.9.1.png",
  },
  {
    id: "f.9.2",
    cluster_id: "F",
    image_id: "f.9",
    url: "/cluster-images/fragments/F/f.9.2.png",
  },
  {
    id: "f.9.3",
    cluster_id: "F",
    image_id: "f.9",
    url: "/cluster-images/fragments/F/f.9.3.png",
  },
];
